### PR TITLE
Py3

### LINKED ISSUE #33: Support python3
Now jubatus doesn't work in py3 environment

### PR DESCRIPTION
**Pull request by unnonouno**
I fixed codes to support py3. Only behavior of `__str__` method of `datum` is different.
In py3, `binary` object is converted to `b'xxx'`, but in py2 `str` is object of course converted to `'xxx'`.
Other differences are written in #33.

fix #33

### CODE REVIEW

**Comment by kmaehashi** [comment]
I'll verify this patch, targeting around ~ April 2015.

**Comment by hirokiky** [comment]
:+1: Some of us really want this.

**Comment by kmaehashi** [comment]
:+1: LGTM

**Comment by hirokiky** [comment]
great job!!!

**Comment by kmaehashi** [comment]
Just for remembrance: Python upstream support status of each version series is as follows (as of today.)

* Python 2.6.9: EOL: https://www.python.org/download/releases/2.6.9/
* Python 2.7.10: maintained: https://www.python.org/downloads/release/python-2710/
* Python 3.0.1: EOL: https://www.python.org/download/releases/3.0.1/
* Python 3.1.5: EOL: https://www.python.org/download/releases/3.1.5/
* Python 3.2.6: maintained: https://www.python.org/downloads/release/python-326/
* Python 3.3.6: maintained: https://www.python.org/downloads/release/python-336/
* Python 3.4.3: latest

**Pull request merged**
